#!/bin/bash
set -e
gitBaseUrl="git@github.com"

cd "$(dirname "$0")"
echo -e "Updating bootstrap ..."
do_force_pull="no"
if [[ -d "./${projectGroup}/${projectName}/.git" ]]; then
  while [[ $# -gt 0 ]]; do
    case $1 in
      --force|-F)
        do_force_pull="yes"
      ;;
    esac
    shift
  done
else
  do_force_pull="yes"
fi

if [[ "${do_force_pull}" == "yes" ]] || git pull origin $(git rev-parse --abbrev-ref HEAD) > /dev/null 2>&1; then
  echo -e "\033[32mAll good to go. Start to pulling all projects\033[0m"
  prefix="$1"
  scripts/projects "${prefix}" | xargs -P10 -I{} scripts/group-branchout "${gitBaseUrl}" {}
  scripts/projects "${prefix}" | xargs -P10 -I{} scripts/project-branchout "${gitBaseUrl}" {}
else
  echo -e "\033[31mFailed to update bootstrap. Please stash or commit your local changes.\n"
fi
