#!/bin/bash

gitBaseUrl="git@github.com"

set -e

cd "$(dirname "$0")"

prefix="$1"
scripts/projects "${prefix}" | xargs -P10 -I{} scripts/group-branchout "${gitBaseUrl}" {}
scripts/projects "${prefix}" | xargs -P10 -I{} scripts/project-branchout "${gitBaseUrl}" {}
