#!/bin/bash
function indexof() {
  echo "$1" "$2" | awk '{print index($1,$2)}'
}

gitBaseUrl="$1"
project="${2}"
pos1="$(indexof $project ':')"
pos2="$(indexof $project '/')"
projectGroup="${project:0:$pos1-1}"
projectGitUrl="${project:$pos1}"
projectName="${project:$pos2}"

set -e
cd "$(dirname "$0")/.."

if [[ -z "${project}" ]]; then
  echo Missing project arg
  exit 1
fi

function logProjectAction() {
  gitBranch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  if test "master" = "${gitBranch}"; then
    echo -e "$1 ${projectGroup}/${projectName} \033[70D\033[70C${gitBranch}"
  else
    echo -e "$1 ${projectGroup}/${projectName} \033[70D\033[70C\033[38;5;11m${gitBranch}\033[0m"
  fi
}

if [[ -d "./${projectGroup}/${projectName}/.git" ]]; then
  cd "${projectGroup}/${projectName}"
  logProjectAction "Pulling"
  git pull --rebase origin > /dev/null 2>&1 || (echo -e "Failed: \033[31m${projectGroup}/${projectName}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m")
else
  cd "${projectGroup}"
  echo -e "Cloning Project: \033[92m${gitBaseUrl}:${projectGitUrl}.git\033[0m"
  if git clone "${gitBaseUrl}:${projectGitUrl}.git" > /dev/null 2>&1; then
    cd "${projectName}"
    logProjectAction "Cloned"
  else
    echo -e "Cloning failed: \033[31m${gitBaseUrl}:${projectGitUrl}.git\033[0m"
  fi
fi
